version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  target-branch: development
  ignore:
  - dependency-name: setuptools
    versions:
    - 53.1.0
    - 54.0.0
    - 54.1.0
    - 54.1.1
    - 54.1.2
    - 54.1.3
  - dependency-name: watchdog
    versions:
    - 2.0.0
    - 2.0.1
